In [1]:
import numpy as np

In [2]:
# define two random matrices and a column vector
a = np.array([[0,0.5],[-1,2]])
b = np.array([[2,-0.5],[3,1.5]])
c = np.array([[1],[-0.5]])

In [3]:
# multiply by scalar
5.*a

array([[ 0. ,  2.5],
       [-5. , 10. ]])

In [4]:
# matrix product
d = np.dot(a,b)
print(a); print(b); print(d)

[[ 0.   0.5]
 [-1.   2. ]]
[[ 2.  -0.5]
 [ 3.   1.5]]
[[1.5  0.75]
 [4.   3.5 ]]


In [5]:
# matrix vector product
e= np.dot(a,c)
print(a);print(c);print(e)

[[ 0.   0.5]
 [-1.   2. ]]
[[ 1. ]
 [-0.5]]
[[-0.25]
 [-2.  ]]


In [6]:
# transpose matrix
a_t = a.transpose()
print(a_t)

[[ 0.  -1. ]
 [ 0.5  2. ]]


In [7]:
# identity matrix
i = np.eye(3,3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
#Compute the norm of c
c_n = np.linalg.norm(c)
print(c_n)

1.118033988749895


In [9]:
#alternative
np.sqrt(c[0]**2+c[1]**2)[0]

1.118033988749895

In [10]:
#determinant of a
a_det = np.linalg.det(a); print(a_det)

0.5


In [11]:
#inverse of a
a_inv = np.linalg.inv(a); print(a_inv)

[[ 4. -1.]
 [ 2.  0.]]


In [12]:
#Checking 
print(np.dot(a_inv,a))

[[1. 0.]
 [0. 1.]]
